### ISSUE TITLE
bug: Uncaught SyntaxError: Unexpected token '<' (at flyonui.js:1:1)

### ISSUE THREAD

**Issue by luchoLoky** [themeselection/flyonui#25]
### What version of FlyonUI are you using?

v1.1.0

### Which browsers are you seeing the problem on?

Edge

### Reproduction URL

https://myserver.com

### Describe your issue

As the title say, my console show this: Uncaught SyntaxError: Unexpected token '<' (at flyonui.js:1:1)

**Comment by PruthviPraj00** [comment]
Hello @luchoLoky,

Could you please describe the issue in more detail? Screenshots or code snippets might be helpful.

Thank you for your understanding.
